services:
  - postgres:12.9

variables:
  POSTGRES_DB: bddmedhead
  POSTGRES_USER: sophonie
  POSTGRES_PASSWORD: qvmsbtkr
  POSTGRES_HOST_AUTH_METHOD: trust

image: maven:latest
stages:          
  - build
  - test
  - package
  - verify
  - install
  #- deploy

build-job:       
  stage: build
  script:
    - mvn clean
    - mvn compiler:compile
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:   
  stage: test    
  script:
    - mvn test-compile
    - mvn test
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

package-job:      
  stage: package  
  script:    
    - mvn package
    - echo "Packaging application..."    
    - echo "Application successfully packaged."

verify-job:
  stage: verify  
  script:
    - mvn verify
    - echo "run any checks to verify the package is valid and meets quality criteria...."            
    - echo "Application successfully verified."
  
install-job:      
  stage: install  
  script:
    - mvn jar:jar install:install
    - echo "Installing application..."            
    - echo "Application successfully installed."

#deploy-job:      
#  stage: deploy  
#  script:
#    - mvn deploy
#    - echo "Deploying application..."            
#    - echo "Application successfully deployed."

